# Generated by Django 2.1.8 on 2019-04-06 11:29

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0038_remove_config_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='flag',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('shared_secret', 'Shared Secret')], default='private', help_text='Please choose if this template should be Public, Private or shared secretly', max_length=16, verbose_name='Flag'),
        ),
        migrations.AddField(
            model_name='template',
            name='variable',
            field=jsonfield.fields.JSONField(blank=True, help_text='Provide values for the list of variables found at the detail page of this template at the Library', null=True, verbose_name='context'),
        ),
    ]
