# Generated by Django 2.1.8 on 2019-04-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0040_config_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='template',
            name='variable',
        ),
    ]
