# Generated by Django 2.1.8 on 2019-04-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0042_templatelibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatelibrary',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='templatelibrary',
            name='vpn',
        ),
        migrations.DeleteModel(
            name='TemplateLibrary',
        ),
    ]
