# Generated by Django 2.1.8 on 2019-04-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0043_auto_20190409_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='flag',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('shared_secret', 'Shared Secret'), ('public', 'Import')], db_index=True, default='private', help_text='Whether to keep this template private or make it public, shared secretly or imported', max_length=16, verbose_name='Flag'),
        ),
    ]
