# Generated by Django 2.1.8 on 2019-04-10 22:49

import django.core.validators
from django.db import migrations, models
import django_netjsonconfig.utils
import re


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0045_auto_20190410_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='key',
            field=models.CharField(db_index=True, default=django_netjsonconfig.utils.get_random_key, help_text='share template key', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[^\\s/\\.]+$'), code='invalid', message='Key must not contain spaces, dots or slashes.')]),
        ),
    ]
